import type { Contact, Product, Order, Campaign, Template, Interaction } from './supabase'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Nutymax Pistache 44g',
    sku: 'GOF.9607',
    quantity: 42048,
    unit_price: 7.00,
    expiry_date: '2026-08-15',
    description: 'Wafer crocante com creme de pistache coberto com chocolate ao leite',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'DuoMax Avelã 44g',
    sku: 'BIS.0705',
    quantity: 33552,
    unit_price: 6.00,
    expiry_date: '2026-07-20',
    description: 'Wafer com recheio de creme de avelã e cacau, coberto com chocolate ao leite',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Biscolata Mood 125g',
    sku: 'BIS.5705',
    quantity: 5064,
    unit_price: 14.00,
    expiry_date: '2026-06-10',
    description: 'Biscoito crocante com recheio cremoso de chocolate e avelã, em embalagem copo',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Biscolata Mood 40g',
    sku: 'BIS.5700',
    quantity: 6624,
    unit_price: 5.50,
    expiry_date: '2026-06-25',
    description: 'Biscoito com recheio de creme de chocolate e avelã, formato individual',
    created_at: new Date().toISOString(),
  },
]

export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'Carlos Mendes',
    company: 'Rede Doces Premium',
    email: 'carlos@rededdoces.com.br',
    phone: '11987654321',
    segment: 'varejo',
    status: 'negociando',
    tags: ['varejo', 'sp'],
    notes: 'Interesse em Nutymax para rede de 12 lojas',
    source: 'indicação',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'Fernanda Lima',
    company: 'Café Gourmet SP',
    email: 'fernanda@cafegourmet.com.br',
    phone: '11976543210',
    segment: 'food-service',
    status: 'proposta-enviada',
    tags: ['food-service', 'coffee-break'],
    notes: 'Usa Mood Copo para coffee break corporativo',
    source: 'importação',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'Roberto Alves',
    company: 'Eventos & Cia',
    email: 'roberto@eventoecia.com.br',
    phone: '11965432109',
    segment: 'eventos',
    status: 'novo',
    tags: ['eventos', 'presente-corporativo'],
    source: 'manual',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'Márcia Souza',
    company: 'Atacadão das Guloseimas',
    email: 'marcia@atacadao.com.br',
    phone: '11954321098',
    segment: 'atacado',
    status: 'fechado',
    tags: ['atacado', 'volume'],
    notes: 'Pedido de R$ 18.000 confirmado',
    source: 'importação',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    name: 'Paulo Rodrigues',
    company: 'Supermercado Pão Doce',
    email: 'paulo@paodoce.com.br',
    phone: '11943210987',
    segment: 'varejo',
    status: 'contatado',
    tags: ['varejo', 'supermercado'],
    source: 'manual',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockTemplates: Template[] = [
  {
    id: '1',
    name: 'Prospecção inicial',
    subject: 'Chocolates turcos premium — amostra grátis para {empresa}',
    body: 'Olá {nome}, trabalho com chocolates turcos premium da marca Sölen — semelhantes ao Ferrero Rocher, porém com origem e sabor únicos. Temos estoque disponível para entrega imediata em SP. Posso enviar uma amostra sem compromisso para vocês experimentarem?',
    channel: 'ambos',
    variables: ['{nome}', '{empresa}'],
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Follow-up (3 dias sem resposta)',
    body: 'Olá {nome}, passando para retomar nosso contato sobre os chocolates Sölen para {empresa}. Temos condição especial de volume disponível esta semana. Posso ligar para apresentar?',
    channel: 'ambos',
    variables: ['{nome}', '{empresa}'],
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Oferta de volume especial',
    body: 'Olá {nome}, tenho uma condição especial de volume disponível para {empresa} esta semana: {produto} com desconto progressivo a partir de R$ 3.000. Entrega em 24h em SP. Interesse em receber uma proposta?',
    channel: 'ambos',
    variables: ['{nome}', '{empresa}', '{produto}'],
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Urgência de estoque',
    body: 'Olá {nome}, comunicado importante: estamos com estoque disponível de {produto} com condição especial por tempo limitado. Temos {quantidade} unidades para entrega imediata. Gostaria de garantir o seu pedido antes que esgote?',
    channel: 'ambos',
    variables: ['{nome}', '{produto}', '{quantidade}'],
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Kit corporativo — Natal',
    subject: 'Kit presente corporativo Sölen — Natal 2026',
    body: 'Olá {nome}, chegou a época de surpreender clientes e colaboradores com algo diferente. Montamos kits de presente corporativo com chocolates turcos premium Sölen — a partir de R$ 55 por kit, com entrega em SP. Posso enviar o catálogo completo?',
    channel: 'email',
    variables: ['{nome}'],
    created_at: new Date().toISOString(),
  },
]

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Prospecção Varejo — Maio 2026',
    channel: 'whatsapp',
    status: 'enviada',
    sent_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    recipient_count: 24,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'Follow-up Food Service',
    channel: 'email',
    status: 'agendada',
    scheduled_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    recipient_count: 12,
    created_at: new Date().toISOString(),
  },
]

export const mockInteractions: Interaction[] = [
  {
    id: '1',
    contact_id: '1',
    type: 'whatsapp',
    notes: 'Enviou catálogo de produtos. Cliente demonstrou interesse.',
    next_action: 'Enviar proposta comercial',
    next_action_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    created_by: 'Victor Hugo',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    contact_id: '1',
    type: 'ligacao',
    notes: 'Apresentou linha completa. Pediu amostras.',
    created_by: 'Victor Hugo',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockOrders: Order[] = [
  {
    id: '1',
    contact_id: '4',
    status: 'pago',
    total: 18000,
    discount_pct: 20,
    channel: 'direto',
    notes: 'Pagamento via PIX',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    contact_id: '2',
    status: 'proposta',
    total: 4200,
    discount_pct: 10,
    channel: 'direto',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
